shinnh2/cpayusin

client/src/App.css, client/src/index.css
- 모든 브라우저에서 동일하게 보이도록 css normalize 코드를 등록했습니다.
- 프로젝트에서 사용할 UI 컬러, 폰트 사이즈, 행간, 그림자 값을 figma를 토대로 css변수로 작성하였습니다. 
- 크게 어려운 점은 없었습니다.
- 추후 작업할 때 어려움이 없도록 설계에 신경쓰고 있습니다.
- 작업한 것을 토대로 기본 컴포넌트도 작업할 예정입니다.
=> [feat/fe-style] CSS 초기 작업

server/src/main/java/com/jbaacount/board/controller/BoardController.java, server/src/main/java/com/jbaacount/board/entity/Board.java, server/src/main/java/com/jbaacount/board/repository/BoardRepositoryCustom.java, server/src/main/java/com/jbaacount/board/repository/BoardRepositoryImpl.java, server/src/main/java/com/jbaacount/board/service/BoardService.java, server/src/main/java/com/jbaacount/category/repository/CategoryRepositoryImpl.java, server/src/test/java/com/jbaacount/board/service/BoardServiceTest.java
board service 테스트 코드 리팩토링
- Hibernate session이 자동으로 동기화 되지 않아 테스트코드 통과가 되지 않았다.
- EntityManager의 refresh를 이용하니 정상적으로 테스트가 통과 되었다.
- 특정 상황(게시판이 삭제)이 발생했을 때 다른 데이터에도 변화(다른 게시판의 orderIndex 수정)가 있다면 refresh를 통해 데이터베이스를 최신 상태로 refresh해야 한다.
-
=> test/be-boardservice 테스트 코드 리팩토링

client/src/App.tsx, node_modules/react-router-dom/package.json
- 각 페이지로 라우팅하기 위해 react-router-dom 설치
- 임의로 Login.tsx를 생성하여 App.tsx에 라우터 컴포넌트 추가
- next.js를 설치하려 했으나 기존 프로젝트와 충돌이 있어 일단 현 상태를 유지하고 react-router-dom을 설치하였습니다.
- 추후 next.js로 마이그레이션 할 예정입니다.
=> [feat/fe-router] 라우터 추가

client/src/App.css, client/src/App.tsx, client/src/components/Input.tsx, client/src/pages/Login.tsx, package.json
- 로그인 화면 생성 후 App.tsx에 라우터 추가
- 로그인 화면 관련 CSS 추가
- input 컴포넌트 수정 
- 크게 어려운 점은 없었습니다.
- 기본 컴포넌트를 미리 제작해 놓으니 화면 구성은 쉬웠습니다.
- 유효성 검사는 추후 별도로 추가할 예정입니다.
=> [feat/fe-login] 로그인 화면 컴포넌트 생성

client/package.json, client/src/App.css, client/src/App.tsx, client/src/components/Header.tsx, client/src/components/Input.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx
- 회원가입 페이지 컴포넌트 생성
- 회원가입 라우터 추가, Header에 페이지 연결
- input 공통 스타일 정리
- input 컴포넌트 수정
- 리액트 라우터에 대해 가물가물?하여 공식문서를 확인하면서 작업하였습니다.
- input 컴포넌트에 '중복 확인' 처럼 버튼이 들어가야 하는 경우가 있기 때문에 공통 컴포넌트를 수정하였습니다.
- 유효성 검사 처리는 별도의 브랜치로 작업할 예정입니다.
=> [feat/fe-signUp] 회원가입 페이지 생성

client/src/App.tsx, client/src/pages/ValidateEmail.tsx
- 이메일 인증 페이지 컴포넌트 생성했습니다.
- 딱히 없습니다.
- 계속해서 화면 작업부터 진행할 예정입니다.
=> [feat/fe-validateEmail] 이메일 인증 페이지 컴포넌트 생성

client/src/App.tsx, client/src/pages/NewPassword.tsx
- 새 비밀번호 입력 페이지 컴포넌트 생성
- 딱히 없습니다.
- 계속 화면작업을 진행할 예정입니다.
=> [feat/fe-newPassword] 새 비밀번호 입력 페이지 컴포넌트 생성

.gitignore, client/src/App.css, client/src/App.tsx, client/src/pages/BoardDetail.tsx, client/src/pages/BoardList.tsx, client/yarn.lock
- 게시글 상세보기 제목 영역 및 정보 영역 화면
- 게시글 상세보기 본문 영역 화면
- 게시글 상세보기 댓글 작성 영역 화면
- 크게 어려운 점은 없었으나 화면 요소 그릴게 많았습니다.
- 특히 댓글을 케이스가 7가지나 됩니다...! 때문에 따로 브랜치를 따로 따서 작업하겠습니다.
- 댓글은 케이스가 7가지 정도 되므로 따로 브랜치를 생성해 작업하겠습니다.
- 경우에 따라 다른 페이지를 먼저 작업할 수도 있습니다.
=> [feat/fe-boardDetail] 게시글 상세보기 페이지 컴포넌트 생성

client/src/App.css, client/src/App.tsx, client/src/pages/UserEdit.tsx
- 유저 정보 페이지 컴포넌트 생성: 화면 작업
- 어려운 점은 없었습니다. 
- 힘들었던 작업 후에 하니까 속도도 빠르고 수월해서 행복했습니다...
- 이미지 업로드 버튼은 추후 필요에 따라 디자인을 넣도록 하고, 일단은 기본 공통 버튼을 사용하겠습니다.
=> [feat/fe-userEdit] 유저 정보 페이지 컴포넌트 생성

client/src/App.css, client/src/pages/UserPage.tsx
- 탭 기능 추가 (관련 이슈: #54) 
- 어려운 점은 딱히 없었습니다.
- 일단은 해당 영역에만 탭 기능을 적용했고, 필요하다고 판단되면 공통으로 분리할 예정입니다.
-
=> [feat/fe-tab] 탭 기능 추가

server/src/main/java/com/jbaacount/comment/controller/CommentController.java, server/src/main/java/com/jbaacount/comment/repository/CommentRepositoryCustom.java, server/src/main/java/com/jbaacount/comment/repository/CommentRepositoryImpl.java, server/src/main/java/com/jbaacount/comment/service/CommentService.java, server/src/main/java/com/jbaacount/post/controller/PostController.java, server/src/main/java/com/jbaacount/post/repository/PostRepositoryCustom.java, server/src/main/java/com/jbaacount/post/repository/PostRepositoryImpl.java, server/src/main/java/com/jbaacount/post/service/PostService.java
=> pagination 변경 Slice -> Page

client/.gitignore
- API URL 환경변수 설정: API 주소가 자주 변경될 예정이므로 환경변수 설정
- gitignore 설정: 환경변수 파일 등록
그간의 API 테스트 결과 API URL이 자주 바뀔 것 같아 쉽게 수정할 수 있도록 환경변수로 등록했습니다.  
크게 어려운 점은 없었습니다.
회원가입 부분이 충돌나서 환경변수를 사용해 다시 작업 후 로그인을 작업할 예정입니다.
=> [feat/fe-env] 환경변수 설정 후 gitignore 수정

client/src/pages/Signup.tsx
- 회원가입 기능 구현
- 회원가입 전송 에러시 에러 상세화
- 이메일 인증 임시 비활성화
- 일단 현재 사정상 기본 회원가입을 먼저 구현했습니다.
- 이전에 작업했던 브랜치가 삭제되었으므로 api 테스트 후 재작업했습니다.
- 하고보니 리팩토링보다는 버그 픽스에 가까운 것 같기도 합니다.
- 이메일 인증은 임시로 비활성화 되었습니다.
- 로그인 등 기본 기능들이 먼저 구현되고 나서 이메일 인증을 추가로 작업할 예정입니다.
=> [Refactor/fe-signupAPI] 회원가입 작업 (기존 브랜치 작업 삭제로 재작업)

client/src/components/Nav.tsx, client/src/pages/BoardList.tsx, client/src/pages/BoardWrite.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx
API 변경으로 인해 api주소, 요청 body 형태 등을 수정하였습니다. 
기존 작업이 잘 되는지 확인하느라 시간이 좀 걸렸지만
단순 변경이라 어려운 점은 없었습니다.
프로젝트 회의에서 테스트해본 결과 게시글 목록을 서버에서 정상적으로 보내주는 것을 확인했습니다.
때문에 이후에는 게시글 목록에서 각 게시글을 클릭했을 때 상세보기로 연결될 수 있도록 작업할 예정입니다.
=> [fix/fe-api] api변경 사항 반영

client/src/pages/BoardDetail.tsx
- 게시물 삭제시 API 연결
- 어렵진 않았으나, 게시물 삭제시 서버에서 정상적으로 응답이 오지만 실제로 게시물 목록에 삭제되지 않고 남아있습니다. 이 부분 백엔드와 협의하여 추후 해결해보도록 하겠습니다.
- 일단은 마이 프로필 부터 작업하도록 하겠습니다.
=> [feat/boardDetailDelete] 게시물 삭제 API 연결

client/src/App.tsx, client/src/components/AdminBoardItem.tsx, client/src/components/Nav.tsx, client/src/pages/Admin.tsx, client/src/pages/BoardDetailEdit.tsx, client/src/pages/BoardWrite.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx, client/src/pages/UserEdit.tsx
- api 리팩토링 및 수정으로 인해 변경사항 반영
- 로그인 실패시 알림창 추가
- 회원가입 성공시 로그인 창으로 이동 추가
- 관리자 페이지 라우터 추가
일단은 api를 연결하여 일부 성공적으로 반영된 것 확인했습니다. 
그러나 아래의 몇가지는 백엔드 측에 문의하여 추가로 테스트할 예정입니다.
- 현재 상태: 로컬 서버로 작업 중입니다. db는 변경되지 않았지만 서버코드는 수정된 코드로 변경하였습니다.
- 문의1: 서버 코드 변경 후, 신규가입한 회원은 로그인이 되지만 기존 회원은 로그인이 되지 않습니다.(관리자 포함)
- 문의2: 수정된 API 문서에 따르면 회원정보 수정시 비밀번호가 필요하지만 테스트 결과 비밀번호가 없어도 회원 정보 수정이 가능했습니다. 이 부분 맞는 것인지 확인하고, 아니라면 UI를 바꿔야 합니다. 따라서 논의가 필요합니다.
- api가 성공적으로 수정되었는지 추가적으로 테스트할 예정입니다.
- 이후 로그인 화면에 소셜 로그인 버튼을 퍼블리싱할 예정입니다.
=> [fix/apiUrl] API 수정사항 반영

client/src/components/AdminBoardItem.tsx, client/src/components/Boarditem.tsx, client/src/components/Nav.tsx, client/src/pages/Admin.tsx, client/src/pages/BoardWrite.tsx, client/src/pages/Login.tsx, client/src/pages/UserPage.tsx
- API 연결 테스트 후 수정 사항 반영
- 테스트 후 발생한 버그나 문제점을 해결하여 반영
이후에는 구글 로그인, 반응형 작업 등을 차례로 작업할 예정입니다.
=> [fix/api] API 연결 테스트 후 수정 반영

client/src/App.css, client/src/App.tsx, client/src/assets/icon_close.svg, client/src/components/Header.tsx, client/src/components/LoginInfo.tsx, client/src/components/NavDrawer.tsx, client/src/pages/BoardDetail.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx
- 반응형 CSS 추가
- 반응형 작업에 따른 일부 컴포넌트 CSS명 수정
- 모바일 전용 네비게이션 드로어(navigation drawer) 추가
- 로그인 전, 후 버튼 영역 공통 컴포넌트 분리 후 적용
- 이미 사전에 반응형을 염두에 두고 작업했기에 딱히 어려운 점은 없었습니다. 
- 다만 모든 페이지를 확인해야 했기에 데이터가 없는 페이지는 더미 데이터를 추가하여 작업 후 다시 제거하느라 전체 작업이 좀 복잡하긴 했습니다.
- 결국 전반적으로 양도 많고 제약사항이 많아 어렵지는 않아도 시간이 좀 걸리는 작업이었습니다. 
이후 다시 소셜 로그인 작업을 하려고 합니다.
=> [feat/responsiveCSS] 반응형 작업

server/src/main/java/com/jbaacount/config/SecurityConfig.java
=> [Refactor] Cors 수정

client/src/App.css, client/src/components/Nav.tsx, client/src/components/SelectBox.tsx, client/src/data/boardData.json, client/src/data/boardListData.json, client/src/data/postData.json, client/src/pages/BoardList.tsx, client/src/pages/BoardWrite.tsx
아래의 버그 및 요청사항 반영
- 모바일에서 하위 게시판 선택이 오른쪽으로 튀어 나가는 현상 수정
- 각 게시판에서 관리자만 쓸 수 있는 경우 표시
- 관리자가 아닌 경우, 관리자만 쓰는 게시판 제외하고 글쓰도록 하기
- 게시글 작성시 에러가 생길 경우 사용자에게 알림창 노출되도록 수정
크게 어려운 점은 없었습니다. 추후 버그가 생기거나 사용자 측면에서 불편한 사항이 생길경우 또 수정하도록 하겠습니다.
JB버그 및 이슈 리포트의 3,4,5,6번을 해결하여 반영했습니다.
=> [fix/board] 게시글 관련 버그 수정 및 요구사항 반영

client/src/App.css, client/src/assets/validater.ts, client/src/components/Header.tsx
- 프론트 유효성 검사 기준 수정(백엔드와 다른 부분 통일시킴)
- 네비게이션 메뉴 화살표 방향 수정
- 헤더 로고 클릭시 홈으로 이동하도록 수정
-
- 확인 결과 이슈 리포트에 취소 버튼 클릭시 동작하지 않는 부분 정상적으로 코드가 적용되어 있던 것 확인했습니다.
추후 같은 문제 발생시 별다른 조치를 취하도록 할 예정입니다. 
- 내가 쓴 게시글, 댓글 부분 API 연결 확인하고 재작업 할 예정입니다.
=> [fix/240711] 버그 및 이슈 해결

client/src/App.css, client/src/components/CommentItem.tsx, client/src/components/CommentListPagination.tsx, client/src/pages/UserPage.tsx
- 마이페이지의 내가 쓴 댓글 목록 API 연결
- 마이페이지 프로필 영역 반응형 CSS 수정
없음
추후 테스트 후에 변경사항이 있다면 fix하겠습니다.
=> [feat/myProfileBoard] 내가 쓴 댓글 목록 

client/src/App.tsx, client/src/pages/Signup.tsx, client/src/pages/ValidateEmail.tsx
- 이메일 인증 복구
- 이메일 인증을 복구하면서 기존과 로직이 조금 달라졌습니다. 때문에 상태를 전역으로 옮기고 API 연결을 하는 과정에서 오타가 나서 애를 먹었습니다... 삽질...
- 빠뜨렸던 투표 기능을 작업하려고 합니다. 이외에 에러만 없으면 작업은 마무리 될 듯 합니다.
=> [fix/emailChk] 

client/src/App.css, client/src/App.tsx, client/src/assets/tokenActions.ts, client/src/components/BoardComment.tsx, client/src/components/CommentListItem.tsx, client/src/components/NavInfo.tsx, client/src/pages/BoardDetail.tsx
- [버그 이슈 리포트 51] 게시글 목록에서 새로고침시 게시글 없어지는 상황 수정 (로딩 문제)
- [버그 이슈 리포트 47] 서버 시간 오류 프론트에서 적용(현지화 기능 사용) 
- [버그 이슈 리포트 52] 삭제된 게시글 스타일 적용
- 토큰 저장 에러 테스트 후 임시 조치
- 토큰 오류로 게시글 렌더링에 오류 발생. 이에 토큰 여부에 따라 분기처리하여 렌더링
- 질문왕 기능 서버 요청 문구 삭제
- 기타 프론트 에러 처리
느낀 점 및 어려운 점을 기록합니다.
해당 작업과 관련된 알림사항 등을 선택적으로 입력합니다.
=> [fix/240818] 이슈 및 버그 수정

client/src/App.tsx, client/src/components/CommentListItem.tsx, client/src/pages/BoardDetailEdit.tsx, client/src/pages/BoardWrite.tsx, client/src/pages/Signup.tsx, client/src/pages/UserEdit.tsx, client/src/pages/ValidateEmail.tsx
- 유저프로필에서 탈퇴시 로그아웃 처리
- 댓글 작성시간 현지화 적용
- 임시 URL 변경 원상복구
- 닉네임 중복검사 추가, 회원가입 실패시 상세 알림 추가
- 회원 탈퇴 처리
- 이메일 중복 확인 추가, 로직 변경
느낀 점 및 어려운 점을 기록합니다.
이제 이미지 포함된 게시글 등록만 해결되면 구축은 끝날 것 같습니다.
=> [fix/240831] 버그 수정
